# Generated by Django 3.2 on 2021-04-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoardDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_disposition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_mos_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('command_now', models.CharField(blank=True, max_length=255, null=True)),
                ('shield_no', models.IntegerField(blank=True, null=True)),
                ('complaint_id', models.IntegerField(blank=True, null=True)),
                ('month_received', models.IntegerField(blank=True, null=True)),
                ('year_received', models.IntegerField(blank=True, null=True)),
                ('month_closed', models.IntegerField(blank=True, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('command_at_incident', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_abbrev_incident', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_abbrev_now', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_now', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_incident', models.CharField(blank=True, max_length=255, null=True)),
                ('mos_age_incident', models.IntegerField(blank=True, null=True)),
                ('complainant_age_incident', models.IntegerField(blank=True, null=True)),
                ('allegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.allegation')),
                ('board_disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.boarddisposition')),
                ('complainant_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_ethnicity', to='new_york_police.ethnicity')),
                ('complainant_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_gender', to='new_york_police.gender')),
                ('contact_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.contactreason')),
                ('fado_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.fado')),
                ('mos_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mos_ethnicity', to='new_york_police.ethnicity')),
                ('mos_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mos_gender', to='new_york_police.gender')),
                ('outcome_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.outcomedescription')),
                ('precinct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_york_police.precinct')),
            ],
        ),
    ]
