# Generated by Django 3.2 on 2021-04-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_york_police', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policecomplaint',
            old_name='complainant_ethnicity',
            new_name='complaint_ethnicity',
        ),
        migrations.RenameField(
            model_name='policecomplaint',
            old_name='complainant_gender',
            new_name='complaint_gender',
        ),
    ]
